server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sharding_db?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root

mybatis:
  type-aliases-package: com.zy.entity
  config-location: classpath:/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: debug
        org.dromara.hmily.demo.bonuspoint: debug
        org.dromara.hmily.demo.lottery: debug
        org.dromara.hmily.demo: debug
        io.netty: info
    path: "./logs"

